In [ ]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv("cdrdata.csv")

In [ ]:
phone_grp = df.groupby(df["Phone Number"])
x = phone_grp.first()["age"]

In [ ]:
for index,rows in df.iterrows():
  df.loc[index,"age"]= x[rows["Phone Number"]]

In [ ]:
df

,Phone Number,Account Length,VMail Message,Day Mins,Day Calls,Day Charge,Eve Mins,Eve Calls,Eve Charge,Night Mins,...,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn,latitude,longitude,time_stamp,age
0,382-4657,128,25,265.1,110,45.07,197.4,99,16.78,244.7,...,23.925115,10.0,3,2.70,1,False,27.579509,77.693033,24-07-2022 22:03,35
1,371-7191,107,26,161.6,123,27.47,195.5,103,16.62,254.4,...,27.080075,13.7,3,3.70,1,False,28.560522,76.770026,25-07-2022 03:45,39
2,358-1921,137,0,243.4,114,41.38,121.2,110,10.30,162.6,...,27.342988,12.2,5,3.29,0,False,27.950405,78.239343,26-07-2022 06:06,40
3,375-9999,84,0,299.4,71,50.90,61.9,88,5.26,196.9,...,23.399288,6.6,7,1.78,2,False,27.870927,77.755536,25-07-2022 03:47,41
4,330-6626,75,0,166.7,113,28.34,148.3,122,12.61,186.9,...,31.812515,10.1,3,2.73,3,False,28.221296,78.280457,25-07-2022 05:48,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101169,789-9756,222,0,228.2,60,22.82,229.8,289,28.26,222.8,...,58.366763,6.2,2,2.62,2,False,28.281947,78.168862,26-07-2022 16:10,35
101170,798-5885,88,0,282.2,222,82.88,208.8,220,22.82,282.2,...,52.582670,9.8,8,2.82,8,False,29.072106,77.624792,26-07-2022 01:45,41
101171,798-5798,22,0,222.2,62,88.66,228.0,228,22.08,62.2,...,54.948890,2.8,6,2.22,2,False,28.068642,76.913950,25-07-2022 23:24,37
101172,999-9897,228,0,222.0,99,88.08,220.2,80,22.92,282.9,...,7.361574,2.2,8,0.82,0,False,28.388485,77.511263,24-07-2022 14:18,36
101173,786-7589,228,0,226.2,98,86.28,288.2,208,28.28,800.0,...,59.944243,20.0,8,2.20,2,False,28.074138,77.113035,26-07-2022 02:15,31

In [ ]:
df.to_csv("corrected_cdr_data.csv")